version: "3.9"
services:
  psql:
    image: postgres:13.2
    environment:
      POSTGRES_PASSWORD: finances-pass
      POSTGRES_USER: postgres
      POSTGRES_DB: financesdevdb
    ports:
      - "5432:5432"
    container_name: postgresql
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
volumes:
  postgres_data: